### ISSUE TITLE
Max Wind Gusts 2 showing Imperial MPH when I specified metric

### ISSUE THREAD

**Issue by ronjtaylor** [garbled1/homeassistant_ecowitt#11]
This is my config in configuration.yaml

ecowitt:
  port: 4199
  barounit: metric
  windunit: metric
  rainunit: metric
#
I have verified that it's 20.2 kph on my display.
I am assuming that windunit in metric would give "kph" not "mph" which is imperial
![image](https://user-images.githubusercontent.com/46874942/88367311-d349af00-cdce-11ea-868a-003bf100d209.png)

By the way I have now installed HACS and loaded Ecowitt from HACS.  Like you said much easier once HACS loaded.

**Comment by garbled1** [comment]
Oops, looks like the conversion is correct but I didn't update the units properly.. Will check this weekend.

**Comment by mr-sneezy** [comment]
I did the install yesterday and I also see Max Daily Wind Gust & Max Daily Wind Gust 2 in imperial instead of metric (with config.yaml windunit set to metric).
![image](https://user-images.githubusercontent.com/6261419/90505562-f9762b00-e191-11ea-8a6d-3b4bea443d48.png)

**Comment by isuee94** [comment]
While we are on the subject...what is the difference between Daily Wind Gust and Daily Wind Gust 2?

**Comment by mr-sneezy** [comment]
I'm not sure, I thought it might reflect two different sample times, maybe 10 minutes and 24 hour.
https://cumuluswiki.org/a/FAQ
See about 1/4 down at the line starting "What do the various wind speeds in Cumulus 1 correspond to, with Fine Offset stations?" where is talks about Fine Offset stations.

The owners manual doesn't explain what it might be as only one type of gust is displayed.  Also describes the various rain values.

6.5.3 Increments of Rain Definitions
 Rain rate or hourly rain is defined as the last 10 minutes of rainfall, multiplied by six (10
minutes x 6 = 1 hour). This is also referred to as instantaneous rain per hour.
 Rain event is defined as continuous rain, and resets to zero if rainfall accumulation is less
than 10 mm (0.039 in) in a 24 hour period.
 Daily Rain is defined as the rainfall since midnight (00:00).
 Weekly Rain is defined as the calendar week total and resets on Sunday morning at midnight
(Sunday thru Saturday).
 Monthly Rain is defined as the calendar month total and resets on the first day of the Month.
 Total Rain is defined as the running total since station was powered up.

6.6 Wind Display
Press the [WIND +] button to switch between average wind speed, wind gust and wind direction.
 Wind speed is defined as the average wind speed in the 16 second update period.
 Wind gust is defined as the peak wind speed in the 16 second update period.

6.7 Temperature Display
If temperature is lower than minimum range, the temperature field will display dashes (--.-).
If temperature is higher than maximum range, the temperature field will display dashes (--.-).
6.7.1 Wind Chill, Dew Point and Heat Index Display
Press the [TEMP] button to switch between Outdoor Temperature, Wind Chill, Heat Index, Dew
Point.

**Comment by garbled1** [comment]
This was fixed in a recent pullup.
