### ISSUE TITLE
unavailable sensor only when using metric

### ISSUE THREAD

**Issue by vincent-d-izo** [garbled1/homeassistant_ecowitt#18]
hello, 
i have an issue when i switch imperial to metric in my config , the related sensor become unvailable.
is there a way or some data i can share to help ?
thks

**Comment by garbled1** [comment]
which sensor is missing?

**Comment by vincent-d-izo** [comment]
every things related to metrics 
rain, wind for example.
thanks a lot for your support

**Comment by garbled1** [comment]
Can you show me your configuration.yaml file, just the ecowitt section.
Also. when you switch from imperial to metric, I think the sensors will have different names, so if you are looking at an existing card, check the entity list to see if new ones show up?

**Comment by vincent-d-izo** [comment]
hello, 
sorry for the very late answer
i try the new version, on a new home assistant os installed on a nuc.
when i choose metric as unit in the integration panel, every rains and winds sensor write " unvailable " as a value
in imperial everything is ok.

**Comment by vincent-d-izo** [comment]
looks like i figured out,
when you switch on metric, it duplicate the sensor.
i supress the old one, and now i have the good one

**Comment by garbled1** [comment]
Yeah, sorry about that.  Generally what I did when I was testing metric was do the switch, and then delete the sensors for imperial.  It's kind of non-ideal because you can't set the options until you've already launched the integration, which picks up the new devices rather quickly...

I guess in theory you could not setup your ecowitt first, and then it won't see them yet.. but...

**Comment by vincent-d-izo** [comment]
No problem, I m glad you made this addon. That the only one which get all
my sensor.

Le jeu. 7 janv. 2021 à 13:21, Tim Rightnour <notifications@github.com> a
écrit :
