### ISSUE TITLE
"Max Daily Wind Gust" and "Max Daily Wind Gust 2" /  Wind Direction, 16-wind rose values & Beaufort Scale  

### ISSUE THREAD

**Issue by zoltari** [garbled1/homeassistant_ecowitt#8]
First of all: Thank you so much for this - it's great to be able to pull information into Home Assistant from the Ecowitt.

Doing this does however present me with two small problems: 

1.  I was using the Custom Ecowitt option in WSTool to send data to WeeWx, which I can't do now .

Is the data your add-on uses stored anywhere after use?  I'm thinking I could maybe manually import into my weather software if it is?   If it's not stored anywhere,  is there perhaps a way that it can be?  I know historical sensor data is stored somewhere because of the sensor history available in Home Assistant, but I don't know how far back it goes.

2.  I use a program called YoWindow: it's a beautiful app that displays interactive representations of the weather.  If you link it to your PWS these scenes will reflect the same weather that's right outside your window, which is really cool (and relaxing to watch when you're thinking).  

To get your PWS's weather data, Yo WIndow requires an .xml file named "yo_cumulus.xml" to be FTPd to it's root directory and kept up-to-date with any changes in weather.  In my case Cumulus or WeeWX generated this file  using a template I got from YoWindow's website:  http://yowindow.com/files/yo_cumulus.txt

The template and weather software create a file named: yo_cumulus.xml  - WeeWX can create this file too, it's just Cumulus is older and used by load of FineOffset stations so yowindow uses that as it's reference.

Is there any way you can generate this yo_cumulus.xml file from the Ecowitt data it receives?

It may sound trivial but yowindow being able to display real-time weather is a really nice thing to have available - plus it's cool.

If anyone can suggest how I might be able to even hack this functionality myself I'd be interested to know.

Thanks for your help and a great add-on too.

**Comment by garbled1** [comment]
Hrmm.. I understand your problem..  the ecowitt will only ever fire data at one port, so you can only have one receiver for it.

I know sensor data is stored inside homeassistant in the SQL db, I personally have mine wired up to fire it down into an influx db, so I can then store it longer, externally.

The second problem is more fiddly.  While I could probably hack something into the code to do that, it's sort of a strange hack and doesn't really fit the model of home-assistant in a reasonable way, and it would kind of be a "just for your one weird case", of which I imagine there are a ton of in the world, which could get messy..  I don't know that something like this is reasonable to put in the component.. :(

So my thoughts are how I would do this if I needed that file:

1) If you wrote an http listener, that captured the data from the ecowitt, and then sent it to two different places at once.  Kind of a weird proxy-relay thing..  something like that might even exist already?  Then send one to HA, and one to weewx?

2) Some kind of custom component in HA that takes weather data and spits out your xml file?

3) Some external API code that asks HA for the current weather data and spits out your xml file?

I suspect 3 would be easiest, if 1 doesn't already exist.

**Comment by zoltari** [comment]
Hi,

Thanks for taking time to reply, I really appreciate it.

Your 1st idea was actually the first thing that occurred to me, but I couldn’t figure out how to do it without a lot of fiddling.  I wanted something simpler if possible.

I’m thinking number 3 might be the way to go, as the data must be in the HA database  somewhere. It’s just finding it that’s eluding me.

I’ve literally only been using HA for ten days, so it’s all pretty new to me.  I’ll work it out how to do this eventually, but it will take me a while I think.

Your 2nd idea is something I (stupidly) hadn’t even thought of: Maybe that’s the way to go in my case.

I totally understand what you’re saying about this being a single use case scenario.  I doubt may people would want to use YoWindow like I am.

Having said that, I know that a LOT of people use some very convoluted methods of obtaining their Ecowitt weather station data for use in WeeWx.  Maybe there’s a case for some kind of historical weather data module in HA?  

Anyway thanks again for making this brilliant module and thank you for getting back to me.

**Comment by Entropy512** [comment]
Yup.  Sadly, due to the limitations of the ecowitt gateway itself, you can only send data to one custom target at a time.

A 4th option not listed (but a significant amount of work) would be to add GW1000 platform support to the likes of Tasmota or ESPHome.  This would require reverse engineering how the RF receiver interfaces with the ESP8266, and also identifying what the attached temp/humidity sensor is.  (Yes, I've opened my GW1000, and it has an ESP8266 inside, so could theoretically be reflashed.  However my motivation to do this reduced greatly once the issue of locking up Home Assistant on startup was resolved.)

Also, as far as item 3, if you're using the influxdb addon, it's probably easier to query influxdb rather than attempt to query HA's internals.  Who knows, it might even work better than just injecting raw data because you could query an average of the last N samples, filtering out some noise?

**Comment by zoltari** [comment]
As I say, Home Assistant is something I’ve literally just started using: I wasn’t aware of the influxdb add on until you mentioned it, so I adde it and have been going through the examples that explain how it works.

  It was my birthday yesterday so I didn’t get much time to take a proper look until today, but from what I’ve seen so far I would say that you’re 100% right about using it being the better option.  I honestly had no idea how powerful influx was until I started playing about with it!  

As regards the ESP platform:  that’s beyond  my abilities but it’s a nice idea.  I don’t know enough about esp to be able to do something like that; maybe one day, but for now, I know my limitations.

It seems to me (from the small amount I’ve seen so far) that with influx I’m going to be able to create a dashboard that pretty much mimics a weather console display, which is all I’m after initially so thanks for putting me on to that.

I don’t mind experimenting to find a solution, but when you’re totally stuck and using a new tool you know nothing about yet, it can be frustrating, so thanks for your ideas and suggestions.  Hopefully  influx is exactly what I was looking for to help me. It certainly seems like it.

**Comment by garbled1** [comment]
I will say this, I personally use Home Assistant as an influx feeder source, and do pretty much all my data analysis on influx/grafana.  I didn't really mention influx, because, it's a bit roundabout of a method..  But it would work..

1) create influxdb, send weather data there (you will like this for other reasons)
2) Write a script that runs every hour or whatever and asks influx for various datapoints, then writes them in xml
3) profit?

The influx API isn't too awful if you just use curl to do it.  The python one is way simpler though IMHO.  XML writing is also much simpler in python than in shell.
