### ISSUE TITLE
Since an update to core 9xx(?) onwards it hasn't worked. Nothing much in the logs either.

### ISSUE THREAD

**Issue by speedracer1190** [garbled1/homeassistant_ecowitt#82]
Hi as mentioned by @GSzabados in https://github.com/garbled1/homeassistant_ecowitt/issues/79#issuecomment-968393868_

I have had an issue where this feature has stopped working since a core update from 9xx to 10.  My model is a WS2900C V2.01.08 with firmware EasyWeatherV1.5.9 
All of the sensors say unavailable. Entities show a red circle at the end in the status column

Only log entry I can find is:  2021-11-14 21:59:40 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration ecowitt which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by isuee94** [comment]
Have you put a version number in the manifest file?

**Comment by GSzabados** [comment]
@isuee94, no need to put version number in the manifest manually, if the component was updated recently from HACS, or manually from the GitHub repo.

@speedracer1190, so first try this:

Go to Configuration/Integrations and search for the Ecowitt integration in the list, click on the 1 device (it should say 1) and then to the device to see what entities are assigned to it. Is is all unavailable?

If yes, then open the WS View or whatever app you used to set up your weather station's settings and check that your settings there are correct, and it sends data to your HA instance.
Weird things can happen with those consoles during a power outage or if you change battery. They can forgot things....

By any chance do you run HA with a fix IP or DHCP? If you use DHCP has the HA IP address changed recently? The weather station has to send data directly to the HA instances IP address. 

Generally follow this for debugging:

https://github.com/garbled1/homeassistant_ecowitt#how-to-set-up

Another issue can be if your HA instance is not receiving the data from the console, due to some internal settings of your installation. All the above assumes, that things are on the same network, and HA is running as a standalone or supervised installation with a supported state.

**Comment by GSzabados** [comment]
@speedracer1190, and make sure that you are running the version 0.7. You can check it in the manifest file.

**Comment by speedracer1190** [comment]
hi @GSzabados Thanks heaps for this.  I had no idea that the it had disconnected when I updated to the WS View Plus app.  I entered the details into that app for my HA and its working fine.

I appreciate your help, thank you.

**Comment by GSzabados** [comment]
@speedracer1190, no worries. Happy to help! :)

Now you can close this issue.
